name: multigrate
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cudatoolkit=10.0
  - jupyterlab
  - matplotlib
  - pandas
  - python=3.7
  - pip
  - pytorch
  - requests
  - scikit-learn
  - seaborn
  - gdown
  - hyperopt
  - torchvision
  - tqdm
  - jupyterlab
  - pip:
    - episcanpy==0.2.2
    - anndata
    - scanpy==1.5.1
