name: scanpy
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cudatoolkit=9.0
  - jupyterlab
  - matplotlib
  - pandas
  - python=3.7.6
  - pip
  - pytorch=1.1.0
  - requests
  - scikit-learn
  - seaborn
  - torchvision=0.3.0
  - tqdm
  - pip:
    - episcanpy==0.1.10
    - anndata==0.7.3
    - scanpy==1.5.1
